# A JupyterHub Helm chart config containing only auth relevant config, and is
# meant to be used alongside another configuration.

custom:
  binderauth_enabled: true

hub:
  services:
    binder:
      oauth_no_confirm: true
      oauth_redirect_uri: "http://127.0.0.1:8585/oauth_callback"
      oauth_client_id: "service-binder-oauth-client-test"
  config:
    JupyterHub:
      authenticator_class: "dummy"
      load_roles:
        - name: user
          scopes: [ 'self', 'access:services' ]
    DummyAuthenticator:
      password: "dummy"
